[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'Eandrju/cellular-automaton.nvim'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'wakatime/vim-wakatime'
